apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: {{ .Values.elasticsearch.image }}
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          ports:
            - containerPort: {{ .Values.elasticsearch.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: {{ .Values.elasticsearch.port }}
      targetPort: {{ .Values.elasticsearch.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: {{ .Values.kibana.image }}
          ports:
            - containerPort: {{ .Values.kibana.port }}
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch:{{ .Values.elasticsearch.port }}"
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  selector:
    app: kibana
  ports:
    - protocol: TCP
      port: {{ .Values.kibana.port }}
      targetPort: {{ .Values.kibana.port }}
